### PR TITLE
Add introduction for effects

### PR DESCRIPTION
**Pull request by patricoferris**
There was one for parallelising OCaml code, this adds a short intro with two videos for effective programming.

cc: @kayceesrk @talex5

### CODE REVIEW

**Comment by kayceesrk** [comment]
It looks good. One thing that might be worth pointing to is that we have the "no syntax version" of effect handlers in 5.00. This means that the examples won't work as-is, but there is an equivalent version using effect functions that will work. This was discussed in [September multicore monthly](https://discuss.ocaml.org/t/multicore-ocaml-september-2021-effect-handlers-will-be-in-ocaml-5-0/8554#why-is-there-no-syntactic-support-for-effect-handlers-in-ocaml-50-2). 

Worth pointing out succinctly without all the details.

**Comment by patricoferris** [comment]
Good point, if I have some spare time over the weekend do you think it is worthwhile porting https://github.com/ocaml-multicore/effects-examples to OCaml 5 (no syntax)? (I think it might, I feel like there's a few gotchas with the syntax-less version with having to use things like `fun (type a) (e : a eff) -> ...` so it might be nice to have a big body of examples in that syntax)?

**Comment by kayceesrk** [comment]
That would be lovely. The state handler ended up need a non trivial type annotation. I can dig that up over the weekend.

**Comment by kayceesrk** [comment]
Here it is: https://gist.github.com/kayceesrk/3c307d0340fbfc68435d4769ad447e10

**Pull request merged**
